apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: kafka
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 2
    parallelism.default: 1
    rest.port: 8081
